"""
Provision external dependencies (DB, Storage, Auth, etc.) for generated projects.
Generates .env and .env.test with mock/local URLs so build and test can run.
Optionally generates docker-compose.test.yml for real service provisioning.
"""

from pathlib import Path
from typing import Any

from core.hlig_dtg_graphs import HLIGGraph

try:
    from core.debug_logger import log_pipeline_event
except ImportError:
    log_pipeline_event = lambda *a, **kw: None


# Mock/local defaults per interface type
MOCK_DEFAULTS = {
    "DB": {
        "DATABASE_URL": "sqlite:///./data/app.db",
        "DB_HOST": "localhost",
        "DB_PORT": "5432",
        "DB_NAME": "app_db",
        "DB_USER": "app_user",
        "DB_PASSWORD": "app_pass",
        "SQLITE_PATH": "./data/app.db",
    },
    "Auth": {
        "AUTH_URL": "http://localhost:9999/auth",
        "AUTH_SECRET": "dev-secret-change-in-production",
        "JWT_SECRET": "jwt-dev-secret",
        "AUTH_DISABLED": "true",  # Allow builds/tests without real auth
    },
    "Filesystem": {
        "STORAGE_PATH": "./storage",
        "UPLOAD_PATH": "./uploads",
    },
    "Storage": {
        "STORAGE_PATH": "./storage",
        "S3_ENDPOINT": "http://localhost:9000",
        "S3_ACCESS_KEY": "minioadmin",
        "S3_SECRET_KEY": "minioadmin",
        "S3_BUCKET": "app-bucket",
    },
    "message": {
        "MESSAGE_QUEUE_URL": "memory://",
        "REDIS_URL": "redis://localhost:6379/0",
    },
    "API": {
        "API_BASE_URL": "http://localhost:3000",
        "EXTERNAL_API_URL": "http://localhost:8080",
    },
}


def _collect_interfaces(hlig_graph: HLIGGraph) -> set[str]:
    """Collect all external_interfaces from HLIG nodes."""
    interfaces: set[str] = set()
    for nid, data in hlig_graph.nodes():
        for iface in data.get("external_interfaces") or []:
            if iface and str(iface) != "None":
                interfaces.add(str(iface).strip())
    return interfaces


def _generate_env_content(interfaces: set[str], mode: str = "test") -> str:
    """Generate .env content from interface set."""
    lines = [
        f"# Auto-generated by PlainSpeak provision_dependencies ({mode} mode)",
        "# Mock/local URLs for build and test",
        "",
    ]
    seen: set[str] = set()
    for iface in sorted(interfaces):
        defaults = MOCK_DEFAULTS.get(iface, MOCK_DEFAULTS.get("API", {}))
        for key, val in defaults.items():
            if key not in seen:
                seen.add(key)
                lines.append(f"{key}={val}")
        if iface not in MOCK_DEFAULTS:
            lines.append(f"# {iface}: add env vars as needed")
    return "\n".join(lines) + "\n"


def _generate_docker_compose(interfaces: set[str]) -> str:
    """Generate docker-compose.test.yml for real services (optional)."""
    services: list[str] = []
    if "DB" in interfaces or "database" in str(interfaces).lower():
        services.append("""  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_pass
      POSTGRES_DB: app_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app_user"]
      interval: 2s
      timeout: 5s
      retries: 5""")
    if "Storage" in interfaces or "message" in interfaces:
        services.append("""  minio:
    image: minio/minio:latest
    command: server /data
    ports:
      - "9000:9000"
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5""")
    if "message" in interfaces:
        services.append("""  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 2s
      timeout: 5s
      retries: 5""")

    if not services:
        return ""

    header = """# Auto-generated by PlainSpeak - run: docker compose -f docker-compose.test.yml up -d
# Use for integration tests with real services

services:
"""
    return header + "\n".join(services) + "\n"


def provision_for_hlig(
    hlig_dir: Path,
    interfaces: set[str],
    session_id: str = "",
    use_docker_compose: bool = False,
) -> list[str]:
    """
    Provision dependencies for one HLIG output directory.
    Creates .env.test and optionally docker-compose.test.yml.

    Returns:
        List of created file paths (relative to hlig_dir)
    """
    created: list[str] = []
    if not interfaces:
        return created

    # .env.test - always generated for mock config
    env_content = _generate_env_content(interfaces)
    env_path = hlig_dir / ".env.test"
    env_path.write_text(env_content, encoding="utf-8")
    created.append(".env.test")

    # .env - copy for convenience (build scripts often read .env)
    env_main = hlig_dir / ".env"
    if not env_main.exists():
        env_main.write_text(env_content, encoding="utf-8")
        created.append(".env")

    # Create data/storage dirs for SQLite and file storage
    for subdir in ("data", "storage", "uploads"):
        d = hlig_dir / subdir
        if not d.exists():
            d.mkdir(parents=True, exist_ok=True)
            created.append(f"{subdir}/")

    # docker-compose.test.yml - optional
    if use_docker_compose:
        dc_content = _generate_docker_compose(interfaces)
        if dc_content:
            dc_path = hlig_dir / "docker-compose.test.yml"
            dc_path.write_text(dc_content, encoding="utf-8")
            created.append("docker-compose.test.yml")

    log_pipeline_event(
        session_id,
        "dependencies_provisioned",
        {"hlig_dir": hlig_dir.name, "interfaces": list(interfaces), "files": created},
    )
    return created


def provision_all(
    hlig_graph: HLIGGraph,
    outputs_dir: Path,
    session_id: str = "",
    use_docker_compose: bool = False,
) -> dict[str, list[str]]:
    """
    Provision dependencies for all HLIG output directories.
    Collects interfaces from graph and provisions each HLIG subdir.

    Returns:
        Dict mapping hlig_id -> list of created files
    """
    all_interfaces = _collect_interfaces(hlig_graph)
    results: dict[str, list[str]] = {}

    for nid, data in hlig_graph.nodes():
        if not data.get("dtg"):
            continue
        hlig_dir = outputs_dir / nid
        if not hlig_dir.exists() or not hlig_dir.is_dir():
            continue
        # Per-node interfaces (or use global if node has none)
        node_interfaces = set()
        for iface in data.get("external_interfaces") or []:
            if iface and str(iface) != "None":
                node_interfaces.add(str(iface).strip())
        if not node_interfaces:
            node_interfaces = all_interfaces
        if node_interfaces:
            created = provision_for_hlig(
                hlig_dir,
                node_interfaces,
                session_id=session_id,
                use_docker_compose=use_docker_compose,
            )
            results[nid] = created

    return results
